apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: monitoring
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  MAILTRAP_USERNAME: {{ .Values.secrets.mailtrapUsername | quote }}
  MAILTRAP_PASSWORD: {{ .Values.secrets.mailtrapPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}