apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: monitoring
type: Opaque
stringData:
  GITHUB_TOKEN:    {{ .Values.secrets.githubToken    | quote }}
  GMAIL_USERNAME:  {{ .Values.secrets.gmailUsername  | quote }}
  GMAIL_PASSWORD:  {{ .Values.secrets.gmailPassword  | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}